name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: display JHIPSTER_TOTO
      run: echo === $JHIPSTER_TOTO ===
      env:
        JHIPSTER_TOTO: ${{ secrets.JHIPSTER_TOTO }}
    # - name: clone JHIPSTER_REPO
    #   run: git clone $JHIPSTER_REPO
    #   env:
    #     JHIPSTER_REPO: ${{ secrets.JHIPSTER_REPO }}
    - name: test inside file
      run: |
        echo "git clone $JHIPSTER_REPO" >> ~/toto.sh
        cat ~/toto.sh
        chmod +x ~/toto.sh
        cd ~/
        ./toto.sh
      env:
        JHIPSTER_REPO: ${{ secrets.JHIPSTER_REPO }}
    - name: test ls generator-jhipster
      run: ls -al ~/generator-jhipster/
