name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: display JHIPSTER_TOTO
      run: echo === $JHIPSTER_TOTO ===
      env:
        JHIPSTER_TOTO: ${{ secrets.JHIPSTER_TOTO }}
    - name: simple echo
      run: |
        echo $GITHUB_REF
        echo $GITHUB_REPOSITORY
      env:
        JHIPSTER_REPO: ${{ secrets.JHIPSTER_REPO }}
    - name: toto
      run: echo $SUPER_SECRET
      env:
        SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
