name: Triage issues
on:
  issues: { types: opened }
jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = { owner: context.issue.owner, repo: context.issue.repo, issue_number: context.issue.number }
            github.issues.listLabelsOnIssue({...issue}).then(response => {
              const labels = response.data
              for (const label of labels) {
                const missingLabel = []
                if (!label.name.includes('area: ')) {
                  missingLabel.push('area: triage')
                }
                if (!label.name.includes('theme: ')) {
                  missingLabel.push('theme: undefined')
                }
                github.issues.addLabels({...issue, labels: missingLabel})
              }
            })
