name: Triage issues
on:
  issues: { types: opened }
jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = { owner: context.issue.owner, repo: context.issue.repo, issue_number: context.issue.number }
            github.issues.listLabelsOnIssue({...issue}).then(response => {
              const labels = response.data
              const missingLabel = []
              const missingArea = true
              const missingTheme = true
              for (const label of labels) {
                if (label.name.includes('area: ')) {
                  missingArea = false
                }
                if (label.name.includes('theme: ')) {
                  missingTheme = false
                }
              }
              if (missingArea) {
                missingLabel.push('area: triage')
              }
              if (missingTheme) {
                missingLabel.push('theme: undefined')
              }
              github.issues.addLabels({...issue, labels: missingLabel})
            })
